version: "3.8"
services:
  backend:
    container_name: contact-book-api
    build:
      context: ./contact-book-api
      dockerfile: Dockerfile
    ports:
      - "10000:10000"

  frontend:
    container_name: contact-book
    build:
      context: ./contact-book
      dockerfile: Dockerfile
    ports:
      - "5173:5173"